name: BattlePlugin
version: '${project.version}'
main: com.github.kumo0621.battleplugin.BattlePlugin
api-version: 1.16
commands:
  battle:
    permission: battle.invite
  startBattle:
    permission: battle.accept
  endBattle:
    permission: battle.accept
permissions:
  battle.invite:
    default: true
  battle.accept:
    default: true

