name: BattlePlugin
version: '${project.version}'
main: com.github.kumo0621.battleplugin.BattlePlugin
api-version: 1.16
commands:
  battlePlugin:
    aliases: battle
    permission: battlePlugin
  startBattle:
     aliases: battleStart
    permission: battlePlugin
  endBattle:
    aliases: battleend
    permission: battlePlugin
permissions:
  battlePlugin:
    default: true
  startBattle:
    default: true
  endBattle:
    default: true

